config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :categories, only: [:index] do
  #   resources :articles, except: [:edit]
  # end

  get '/categories', to: 'categories#index'
  get '/categories/:category_id/articles', to: 'articles#index', as: 'category_articles'
  post '/categories/:category_id/articles', to: 'articles#create'
  get '/categories/:category_id/articles/new', to: 'articles#new', as: 'new_category_article'
  get '/categories/:category_id/articles/:id', to: 'articles#show', as: 'category_article'
  patch '/categories/:category_id/articles/:id', to: 'articles#update'
  put '/categories/:category_id/articles/:id', to: 'articles#update'
  delete '/categories/:category_id/articles/:id', to: 'articles#destory'
  get '/categories/:category_id/articles/:id/edit/:code', to: 'articles#edit', as: 'edit_category_article'

  post '/users', to: 'users#create', as: 'users'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/new', to: 'users#new', as: 'new_user'

  # resources :users, only: [:show, :create, :new]

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'session', to: 'sessions#inspect'

  root 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
require 'securerandom'

class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :article_tags
  has_many :tags, through: :article_tags

  before_create :generate_edit_id

  validates :title, :description, :email, { presence: true}

  def generate_edit_id
    self.edit_id = SecureRandom.hex(6)
  end
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :article_tags
  has_many :articles, through: :article_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles

  validates :email, presence: true, uniqueness: { case_sensitive: false }

  has_secure_password

  # BCrypt
  def password
    @password ||= BCrypt::Password.new(password_digest)
  end

  def password=(new_password)
    @password = BCrypt::Password.create(new_password)
    self.password_digest = @password
  end

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    return false if user.nil?
    user.password == password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @category = Category.find_by(id: params[:category_id])
  end

  def create
    @category = Category.find_by(id: params[:category_id])
    @article = @category.articles.new(article_params)
    if helpers.current_user
      @article.user = helpers.current_user
    end
    if @article.save
      session[:edit_code] = @article.edit_id
      redirect_to category_article_url(@category, @article)
    else
      render 'new'
    end
  end

  def new
    @category = Category.find_by(id: params[:category_id])
    @article = @category.articles.new()
  end

  def show
    @article = Article.find_by(id: params[:id])
    @category = @article.category
  end

  def update
    @article = Article.find_by(id: params[:id])

    if @article.update(article_params)
      redirect_to category_article_url(@article.category, @article)
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find_by(id: params[:id])
    @article.destroy
    redirect_to root_path
  end

  def edit
    @article = Article.find_by(id: params[:id])
    @category = @article.category
    if @article.edit_id != params[:code]
      redirect_to category_article_url(@category, @article)
    else
      render 'edit'
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :email, :price, :zip_code, :description)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    categories = Category.order(:name)
    count = categories.length / 4
    counter = 0
    @cat_array = []
    4.times do
      arry = []
      count.times do
        arry << categories[counter]
        counter += 1
      end
      @cat_array << arry
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new()
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if User.authenticate(params[:session][:email], params[:session][:password])
      helpers.log_in(@user)
      redirect_to @user
    else
      @errors = ["invalid email or password"]
      render 'new'
    end
  end

  def destroy
    helpers.log_out
    redirect_to root_path
  end

  def inspect
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if helpers.logged_in?
      redirect_to helpers.current_user
    else
      @user = User.new()
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      helpers.log_in(@user)
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
  end

  def show
    if !helpers.logged_in?
      redirect_to login_url
    end
  end

  private
  def user_params
    params.require(:user).permit(:password, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def pretty_time(time)
    time.strftime('%b %-d')
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @user ||= User.find_by_id(session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @user = nil
  end
end

app/views/articles/_form.html.erb
<br>
<%= form_for [@category, @article] do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation" class="is-danger">
      <p>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </p>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label      :title, class: 'label' %>
    <p class="control">
      <%= f.text_field :title, class: 'input' %>
    </p>
  </div>
  <div class="field">
<% if current_user %>
    <%= f.label       :email, class: 'label' %>
    <p class="control">
      <%= f.email_field :email, value: current_user.email, class: 'input' %>
    </p>
<% else %>
    <%= f.label       :email %>
    <p class="control">
      <%= f.email_field :email, value: current_user.email, class: 'input' %>
    </p>
<% end %>
  </div>
  <div class="field">
    <%= f.label      :price, class: 'label' %>
    <p class="control">
      <%= f.text_field :price, class: 'input' %>
    </p>
  </div>
  <div class="field">
    <%= f.label       :zip_code, class: 'label' %>
    <p class="control">
      <%= f.text_field  :zip_code, class: 'input' %>
    </p>
  </div>
  <div class="field">
    <%= f.label     :description, class: 'label' %><br>
    <p class="control">
      <%= f.text_area :description, class: 'textarea' %>
    </p>

  <div class="field">
    <p class="control">
      <%= f.submit 'Submit', class: 'button is-primary' %>
    </p>
  </div>
<% end %>

app/views/articles/edit.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <%= @category.name %>
      </h1>
      <h2 class="subtitle">
        edit post | <%= link_to 'delete post', [@category, @article], method: :delete, data: { confirm: 'Are you sure?' }, class: 'but' %>
      </h2>
    </div>
    <div class="container">
      <div class="content">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/articles/index.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <%= @category.name %>
      </h1>
      <h2 class="subtitle">
        <%= link_to 'new post', new_category_article_path, id: 'new-post' %>
      </h2>
    </div>
    <div class="container">
      <div class="content">
        <ul>
        <% @category.articles.order(:updated_at).each do |article| %>
          <li><%= pretty_time(article.updated_at) %> - <%= link_to(article.title, category_article_url(@category, article)) %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/articles/new.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <%= @category.name %>
      </h1>
      <h2 class="subtitle">
        new post
      </h2>
    </div>
    <div class="container">
      <div class="content">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/articles/show.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <%= @article.title.downcase %>
      </h1>
      <h2 class="subtitle">
        <%= @article.category.name %>
      </h2>
    </div>
    <br>
    <div class="container">
      <div class="content">
<p>Price: $<%= @article.price %></p>
<p><%= @article.description %></p>
<p>Zip Code: <%= @article.zip_code %></p>
<% if session[:edit_code] %>
  <p>You may edit or delete your entry by going to <%= link_to(edit_category_article_url(@category, @article, @article.edit_id), edit_category_article_url(@category, @article, @article.edit_id)) %></p>
<% end %>
<% session.delete(:edit_code) %>

app/views/categories/index.html.erb
<section class="section">
  <div class="container">
    <div class="content">
      <div class="columns">
<% @cat_array.each do |columns| %>
        <div class="column is-quarter">
        <% columns.each do |category| %>
          <%= link_to category.name, category_articles_path(category) %><br>
        <% end %>
        </div>
<% end %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CraigslistJr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav class="nav has-shadow">
  <div class="nav-left">
    <%= link_to 'craigslist jr', root_path, class: 'nav-item' %>
  </div>
  <div class="nav-right">
  <% if current_user %>
  <%= link_to 'profile', @user, class: 'nav-item' %>
  <%= link_to 'logout', logout_path, method: :delete, class: 'nav-item' %>
<% else %>
  <%= link_to 'register', new_user_path, class: 'nav-item' %>
  <%= link_to 'login', login_path, class: 'nav-item' %>
<% end %>
</nav>
  <%= yield %>
</div>
</body>
</html>

app/views/users/new.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        register
      </h1>
    </div>
    <br>
    <div class="container">
      <div class="content">
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation" class="is-danger">
      <p>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </p>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li class='is-danger'><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <br>
  <% end %>
  <div class="field">
    <%= f.label       :email, class: 'label' %>
    <p class="control">
      <%= f.email_field :email, class: 'input' %>
    </p>
  </div>
  <div class="field">
    <%= f.label          :password, class: 'label' %>
    <p class="control">
      <%= f.password_field :password, class: 'input' %>
    </p>
  </div>
  <div class="field">
    <p class="control">
      <%= f.submit 'register', class: 'button is-primary' %>
    </p>
  </div>
<% end %>

app/views/users/show.html.erb
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        my profile
      </h1>
    </div>
    <br>
    <div class="container">
      <div class="content">
        <p>My Email: <%= current_user.email %></p>
        <p>My posts:</p>
        <ul>
        <% if @user.articles.empty? %>
          <li>No Posts</li>
        <% end %>
        <% @user.articles.each do |post| %>
          <li><%= link_to post.title, category_article_path(post.category, post) %> - <%= link_to 'edit', edit_category_article_path(post.category, post, post.edit_id) %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</section>